use crate::traits::PresetInfo;

use super::PythonAppPreset;

impl PresetInfo for PythonAppPreset {
    fn name(&self) -> &str {
        "python-app"
    }

    fn description(&self) -> &str {
        "CI pipeline for Python applications with pytest, linting, and type checking"
    }
}

// EditorPreset implementation is now auto-generated by #[derive(Preset)]
