[package]
name = "cibox-macros"
version = "0.0.1"
edition = "2021"
authors = ["cilki"]
description = "Control your CI/CD"
license = "Unlicense"
repository = "https://github.com/fossable/cibox"
keywords = ["ci", "github-actions", "gitlab-ci", "automation"]
categories = ["command-line-utilities", "development-tools"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "3.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
darling = "0.24"
